apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ssh
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ssh
  template:
    metadata:
#      annotations:
#        security.alpha.kubernetes.io/unsafe-sysctls: kernel.msgmnb=13107200,kernel.msgmni=256,kernel.msgmax=65536,kernel.shmmax=69719476736,kernel.sem=500 256000 250 1024
      labels:
        app: web-ssh
    spec:
#      nodeSelector:
#        cslckind1: test
      containers:
      - name: web-ssh
#        image: snsyzb/webssh
        image: bwsw/webshell
#        imagePullPolicy: Never
        ports:
        - containerPort: 8080
       

---
apiVersion: v1
kind: Service
metadata:
  name: web-ssh-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: web-ssh
  ports:
  - protocol: TCP
#    port: 8080
#    nodePort: 30022
#    targetPort: 8080
    port: 80
    nodePort: 30022
    targetPort: 80
