apiVersion: v1
kind: Service
metadata:  
  namespace: kube-ops
  name: jenkins-nodeport-service
spec:
  type: NodePort
  selector:
    app: jenkins2
  ports:  
  - port: 8080
    name: "http"
    targetPort: 8080
    nodePort: 30000
  - port: 50000
    name: "slave"
    targetPort: 50000
    nodePort: 30010
