---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mq-data
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: "my-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
